column_names:
  - match
  - competition
  - date
  - position
  - minutes_played
  - total_actions
  - successful_actions
  - goals
  - assists
  - shots
  - shots_on_target
  - xg
  - passes
  - accurate_passes
  - long_passes
  - accurate_long_passes
  - crosses
  - accurate_crosses
  - dribbles
  - successful_dribbles
  - duels
  - duels_won
  - aerial_duels
  - aerial_duels_won
  - interceptions
  - losses
  - losses_own_half
  - recoveries
  - recoveries_opp_half
  - yellow_cards
  - red_cards
  - defensive_duels
  - defensive_duels_won
  - loose_ball_duels
  - loose_ball_duels_won
  - sliding_tackles
  - sliding_tackles_successful
  - clearances
  - fouls
  - shot_assists
  - offensive_duels
  - offensive_duels_won
  - touches_in_penalty_area
  - offsides
  - progressive_runs
  - fouls_suffered
  - through_passes
  - through_passes_accurate
  - xa
  - second_assists
  - passes_to_final_third
  - passes_to_final_third_accurate
  - passes_to_penalty_area
  - passes_to_penalty_area_accurate
  - received_passes
  - forward_passes
  - forward_passes_accurate
  - back_passes
  - back_passes_accurate
  - conceded_goals
  - xcg
  - shots_against
  - saves
  - saves_with_reflexes
  - exits
  - passes_to_gk
  - passes_to_gk_accurate
  - goal_kicks
  - short_goal_kicks
  - long_goal_kicks
  - home_team
  - away_team
  - year
  - team
  - player_name


metrics:
  total_passing_accuracy: ["accurate_passes", "passes"]
  forward_passing_accuracy: ["forward_passes_accurate", "forward_passes"]
  long_passing_accuracy: ["accurate_long_passes", "long_passes"]
  total_duel_win_rate: ["duels_won", "duels"]
  aerial_duel_win_rate: ["aerial_duels_won", "aerial_duels"]
  defensive_duel_win_rate: ["defensive_duels_won", "defensive_duels"]
  shot_on_target_rate: ["shots_on_target", "shots"]
  xg_per_shot: ["xg", "shots"]
  gk_stat_save_pct: ["saves", "shots_against"]
  crossing_accuracy: ["crosses", "accurate_crosses"]
  dribbles_accuracy: ["dribbles", "successful_dribbles"]


columns_config:
  Forwards:
    column_names:
      aerial_duels_won: Aerial Duels Won
      aerial_duels: Aerial Duels
      xg: Expected Goals (xG)
      progressive_runs: Progressive Runs Attempted
      shots: Shots
      shots_on_target: Shots on Target
      shot_assists: Shot Assists
      touches_in_penalty_area: Touches Inside the Box
      recoveries: Recoveries
      recoveries_opp_half: Recoveries in Opponent's Half

  Wingers:
    column_names:
      dribbles: Dribbles Attempted
      successful_dribbles: Successful Dribbles
      crosses: Crosses Attempted
      accurate_crosses: Accurate Crosses
      recoveries: Recoveries
      recoveries_opp_half: Recoveries in Opponent's Half
      defensive_duels: Defensive Duels Attempted
      defensive_duels_won: Defensive Duels Won
      duels: Duels Attempted
      duels_won: Duels Won

  Attacking Midfielders:
    column_names:
      through_passes: Through Passes Attempted
      through_passes_accurate: Through Passes Completed
      passes_to_penalty_area: Passes Into Box Attempted
      passes_to_penalty_area_accurate: Passes Into Box Completed
      recoveries: Recoveries
      recoveries_opp_half: Recoveries in Opponent's Half
      loose_ball_duels: Loose Ball Duels Attempted
      loose_ball_duels_won: Loose Ball Duels Won
      touches_in_penalty_area: Touches Inside the Box

  Central Midfielders:
    column_names:
      aerial_duels: Aerial Duels Attempted
      aerial_duels_won: Aerial Duels Won
      xg: Expected Goals (xG)
      progressive_runs: Progressive Runs Attempted
      touches_in_penalty_area: Touches Inside the Box
      shots: Shots
      shots_on_target: Shots on Target
      recoveries: Recoveries
      recoveries_opp_half: Recoveries in Opponent's Half

  Defensive Midfielders:
    column_names:
      accurate_passes: Total Passes Completed
      forward_passes_accurate: Forward Passes Completed
      aerial_duels_won: Aerial Duels Won
      recoveries: Recoveries
      shots_on_target: Shots on Target
      shots: Shots
      shot_assists: Shot Assists

  Center Backs:
    column_names:
      aerial_duels: Aerial Duels Attempted
      aerial_duels_won: Aerial Duels Won
      defensive_duels: Defensive Duels Attempted
      defensive_duels_won: Defensive Duels Won
      long_passes: Long Passes Attempted
      accurate_long_passes: Long Passes Completed
      passes: Total Passes Attempted
      accurate_passes: Total Passes Completed
      forward_passes: Total Forward Passes Attempted
      forward_passes: Total Forward Passes Completed

  Outside Backs:
    column_names:
      shots: Shots
      shots_on_target: Shots on Target
      crosses: Attempted Crosses
      accurate_crosses: Total Crosses Completed
      losses: Losses
      recoveries: Recoveries
      recoveries_opp_half: Recoveries in Opponent's Half
      passes_to_final_third: Passes to Final Third Attempted
      passes_to_final_third_accurate: Passes to Final Third Completed
        
  Goalkeepers:
    column_names:
      xcg: xG Conceded
      conceded_goals: Goals Conceded
      saves: Saves Made
      gk_stat_save_pct: Save Percentage
      shots_against: Shots Faced